### PR TITLE
Add README.md and candidates folder

### PR DESCRIPTION
**Pull request by openstacker**

### CODE REVIEW

**Comment by openstacker** [comment]
@Vincenttoolate Hi Vincent, here is the PR based on our discussion this noon. I will add more details soon. Thanks for volunteering for this exciting program. Cheers.

**Review by quintuschen — COMMENTED** [review]
- Do we need to have the format/form of EOI?
- When a mentor nominates himself/herself, what form shall he/she take? Does he/she need to submit a proposal to CITA?

**Comment by openstacker** [comment]
@quintuschen I have created a EOI form here https://docs.google.com/forms/d/e/1FAIpQLScvpIbldjLlISEia6nS_MSVbmLySg7mmQ_3j3gXHQ_Coc1SQQ/viewform

For this first round, we have selected those mentors. But in the future, we would like to have a nomination from mentors who would like to nominate themselves.

**Comment by alex-zige** [comment]
👍 merged in first.

**Pull request merged**
